/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import game_mgr from "./game/game_mgr"
import hammer from "./game/hammer"
import mouse from "./game/mouse"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("game/game_mgr.js",game_mgr);
		reg("game/hammer.js",hammer);
		reg("game/mouse.js",mouse);
    }
}
GameConfig.width = 960;
GameConfig.height = 640;
GameConfig.scaleMode ="fixedheight";
GameConfig.screenMode = "none";
GameConfig.alignV = "top";
GameConfig.alignH = "left";
GameConfig.startScene = "game_scene.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
